In [58]:
import torch.nn as nn
import torch.utils.model_zoo as model_zoo
import torch

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

In [59]:
from Dataset.UEset import UEset
from models.vgg import vgg16_bn_tiny
from models.resnet import ResNet10

In [60]:
a1 =torch.tensor([0,1])
a2 =torch.tensor([1,0])

In [61]:
a1+a2

tensor([1, 1])

In [62]:
torch.sum(a1,a2)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [63]:
torch.mean([a1,a2],dim=0)

TypeError: mean() received an invalid combination of arguments - got (list, dim=int), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [64]:
pre_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((224,224)),
    ])
root = '/remote-home/share/MM_Ultrasound'

In [65]:
data = UEset(root, pre_transform = pre_transform, sub_list = [1,2,3,4,5],label=True)

In [72]:
len(data)

3474

In [67]:
for i in range(len(data)):
    imgs, label = data[i]
    print(label)
    

tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)

tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)

tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)

tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)

tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(1.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)

In [5]:
loader = DataLoader(data,batch_size=256,shuffle=True,num_workers=4)

In [6]:
for imgs, label in loader:
    print(imgs.shape)

torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([256, 4, 3, 224, 224])
torch.Size([146, 4, 3, 224, 224])


In [15]:
from models.encoder import Res_Encoder
model = Res_Encoder()

In [31]:
class Res_Encoder(nn.Module):
    def __init__(self, input_dim=3, L=500, D=128, K=1):
        super(Res_Encoder, self).__init__()
        self.input_dim = input_dim
        self.L = L
        self.D = D
        self.K = K

        self.feature_extractor_part1 = ResNet10()

        self.feature_extractor_part2 = nn.Sequential(
            nn.Linear(512 * 7 * 7, self.L),
            nn.ReLU(),
        )

        self.attention = nn.Sequential(
            nn.Linear(self.L, self.D),
            nn.Tanh(),
            nn.Linear(self.D, self.K)
        )

    def forward(self, x, debug=False):

        batch = x.shape[0]
        x = x.view(-1,3,224,224)
        print(x.shape)
        f = self.feature_extractor_part1(x)
        f = f.view(-1,512*7*7)
        print(f.shape)
        
        f = self.feature_extractor_part2(f)
        f = f.view(batch,4,-1)

    

        return f

In [32]:
input = torch.randn((128,4,3,224,224))

In [33]:
model = Res_Encoder()

In [34]:
output = model(input)

torch.Size([512, 3, 224, 224])
torch.Size([512, 25088])


In [35]:
output.shape

torch.Size([128, 4, 500])

In [36]:
f11 = output[:,0,:]

In [37]:
f11.shape

torch.Size([128, 500])

In [5]:
imgs, label = data[19]

In [9]:
img11, img21, img12, img22 = imgs

In [11]:
img11.shape

torch.Size([3, 224, 224])

In [13]:
model = vgg16_bn_tiny()

In [22]:
output = model(img11.unsqueeze(0))

In [25]:
len(output)

5

In [27]:
model2 = ResNet10()

In [29]:
model2(img11.unsqueeze(0)).shape

torch.Size([1, 512, 7, 7])

In [ ]:
class Res_Attention(nn.Module):
    def __init__(self, input_dim=3, L=500, D=128, K=1):
        super(Res_Attention, self).__init__()
        self.input_dim = input_dim
        self.L = L
        self.D = D
        self.K = K

        self.feature_extractor_part1 = ResNet10()

        self.feature_extractor_part2 = nn.Sequential(
            nn.Linear(512 * 7 * 7, self.L),
            nn.ReLU(),
        )


## For InfoNCE

In [38]:
# 256 imgs with dim 512
f11 = torch.randn(256,512)
f21 = torch.randn(256,512)
f12 = torch.randn(256,512)
f22 = torch.randn(256,512)

In [44]:
f11.size(0)

256

In [39]:
criterion = nn.CrossEntropyLoss()

In [41]:
t = 0.01
# for data augmentation loss
l_pos_aug1 = torch.einsum('nc,nc->n',[f11,f12]).unsqueeze(-1)
l_pos_aug2 = torch.einsum('nc,nc->n',[f21,f22]).unsqueeze(-1)
l_neg_aug1 = torch.einsum('nc,ck->nk',[f11,f12.T])
l_neg_aug2 = torch.einsum('nc,ck->nk',[f21,f22.T])
logits_aug1 = torch.cat([l_pos_aug1,l_neg_aug1],dim=1)
logits_aug2 = torch.cat([l_pos_aug2,l_neg_aug2],dim=1)
labels = torch.zeros(logits_aug1.shape[0],dtype=torch.long)
aug_loss = criterion(logits_aug1,labels) + criterion(logits_aug2,labels)


In [42]:
labels.shape

torch.Size([256])

In [47]:
# for domain invariant loss
l_pos_d1 = torch.einsum('nc,nc->n',[f11,f21]).unsqueeze(-1)
l_pos_d2 = torch.einsum('nc,nc->n',[f12,f22]).unsqueeze(-1)
l_neg_d1 = torch.einsum('nc,ck->nk',[f11,f21.T])
l_neg_d2 = torch.einsum('nc,ck->nk',[f12,f22.T])
logits_d1 = torch.cat([l_pos_d1,l_neg_d1],dim=1)
logits_d2 = torch.cat([l_pos_d2,l_neg_d2],dim=1)
labels = torch.zeros(logits_d1.shape[0],dtype=torch.long)
d_loss = criterion(logits_d1,labels) + criterion(logits_d2,labels)

In [48]:
aug_loss

tensor(127.3748)

In [49]:
d_loss

tensor(130.3878)

## draft for prediction

In [29]:
prob = torch.randn(5,2)

In [30]:
prob

tensor([[-0.8591, -0.8592],
        [ 0.1835,  1.0775],
        [ 0.6239, -1.1920],
        [-0.9117, -0.7077],
        [-0.5845, -0.5312]])

In [31]:
a = torch.argmax(prob,dim=1)

In [38]:
a

tensor([0, 1, 0, 1, 1])

In [36]:
softmax_prob = torch.softmax(prob,dim=1)

In [37]:
softmax_prob

tensor([[0.5000, 0.5000],
        [0.2903, 0.7097],
        [0.8601, 0.1399],
        [0.4492, 0.5508],
        [0.4867, 0.5133]])

In [70]:
prob = softmax_prob[:,1]

In [71]:
prob

tensor([0.5000, 0.7097, 0.1399, 0.5508, 0.5133])

In [42]:
prob, pred = torch.max(softmax_prob,dim=1)

In [68]:
prob

tensor([0.5000, 0.7097, 0.8601, 0.5508, 0.5133])

In [69]:
pred

tensor([0, 1, 0, 1, 1])

In [52]:
p=[]

In [55]:
p.extend(prob.cpu().detach().tolist())

In [56]:
p

[0.5000395774841309,
 0.7097166776657104,
 0.8600674867630005,
 0.5508385896682739,
 0.5133243203163147,
 0.5000395774841309,
 0.7097166776657104,
 0.8600674867630005,
 0.5508385896682739,
 0.5133243203163147]

In [49]:
p.append(prob.cpu().detach().numpy().ravel())

In [50]:
p

[array([0.5000396, 0.7097167, 0.8600675, 0.5508386, 0.5133243],
       dtype=float32),
 array([0.5000396, 0.7097167, 0.8600675, 0.5508386, 0.5133243],
       dtype=float32)]

In [45]:
prob.cpu().detach().numpy().ravel()

array([0.5000396, 0.7097167, 0.8600675, 0.5508386, 0.5133243],
      dtype=float32)

In [44]:
pred

tensor([0, 1, 0, 1, 1])

In [32]:
a.tolist()

[0, 1, 0, 1, 1]

In [28]:
label = [1,1,1,1,1]

In [27]:
from sklearn.metrics import classification_report, roc_auc_score, roc_curve, accuracy_score

In [34]:
classification_report(label,a.tolist(),output_dict = True, zero_division=0)

{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0},
 '1': {'precision': 1.0,
  'recall': 0.6,
  'f1-score': 0.7499999999999999,
  'support': 5},
 'accuracy': 0.6,
 'macro avg': {'precision': 0.5,
  'recall': 0.3,
  'f1-score': 0.37499999999999994,
  'support': 5},
 'weighted avg': {'precision': 1.0,
  'recall': 0.6,
  'f1-score': 0.7499999999999999,
  'support': 5}}

## test for vgg encoder

In [99]:
from models.vgg import vgg16_bn_tiny
encoder = vgg16_bn_tiny()

In [1]:
input = torch.randn(2,3,224,224)
a = encoder(input)

NameError: name 'torch' is not defined

In [2]:
for f in a:
    print(f.shape)

NameError: name 'a' is not defined

In [103]:
def l2_normal(x,dim=1):
    norm = x.pow(2).sum(dim, keepdim=True).pow(1./2)+1e-10
    out = x.div(norm)
    return out
            
def l1_normal(x,dim=1):
    x=x+10e-10
    norm = x.sum(dim, keepdim=True)
    out = x.div(norm)
    return out  

class decoder(nn.Module):
    def __init__(self,channel_list=[128,128,64,32,16,32,8]):
        super(decoder, self).__init__()
        self.upsample=nn.Upsample(scale_factor=(2,2))
        
        
        self.conv_layer8x=nn.Sequential(
                                              nn.Conv2d(in_channels=channel_list[0]+channel_list[1],out_channels=channel_list[1],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[1]),
                                              nn.ReLU(True),
                                              nn.Conv2d(in_channels=channel_list[1],out_channels=channel_list[2],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[2]),
                                              nn.ReLU(True))

        self.conv_layer4x=nn.Sequential(
                                              nn.Conv2d(in_channels=channel_list[2]*2,out_channels=channel_list[2],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[2]),
                                              nn.ReLU(True),
                                              nn.Conv2d(in_channels=channel_list[2],out_channels=channel_list[3],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[3]),
                                              nn.ReLU(True)
                                                )
        self.conv_layer2x=nn.Sequential(
                                              nn.Conv2d(in_channels=channel_list[3]*2,out_channels=channel_list[3],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[3]),
                                              nn.ReLU(True),
                                              nn.Conv2d(in_channels=channel_list[3],out_channels=channel_list[4],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[4]),
                                              nn.ReLU(True)
                                                )
        self.embedding_branch=nn.Sequential(
                                              nn.Conv2d(in_channels=channel_list[4]*2,out_channels=channel_list[5],kernel_size=(3,3),padding=(1,1)),
                                              nn.BatchNorm2d(channel_list[5]),
                                              nn.ReLU(True),
                                              nn.Conv2d(in_channels=channel_list[5],out_channels=channel_list[5],kernel_size=(3,3),padding=(1,1))
                                                )
        if len(channel_list)>6:
            self.clustering_branch=nn.Sequential(
                                                  nn.Conv2d(in_channels=channel_list[4]*2,out_channels=channel_list[6],kernel_size=(3,3),padding=(1,1)),
                                                  nn.BatchNorm2d(channel_list[6]),
                                                  nn.ReLU(True),
                                                  nn.Conv2d(in_channels=channel_list[6],out_channels=channel_list[6],kernel_size=(3,3),padding=(1,1)),
                                                  nn.Sigmoid()
                                                )
    def forward(self, x,region_output_size=(4,4),if_clustering=False,if_test=False):
        features=self.upsample(x[-1])
        print(features.shape)
        features=torch.cat([features,x[-2]],dim=1)
        features=self.conv_layer8x(features)
        features=self.upsample(features)
        features=torch.cat([features,x[-3]],dim=1)
        features=self.conv_layer4x(features)
        features=self.upsample(features)
        features=torch.cat([features,x[-4]],dim=1)
        features=self.conv_layer2x(features)
        features=self.upsample(features)
        features=torch.cat([features,x[-5]],dim=1)
        del x
        if not if_clustering:
            features=self.embedding_branch(features)
            features=l2_normal(features)
            return features
        
        attention_map=self.clustering_branch(features)
        attention_map=l1_normal(attention_map, dim=1)
        features=self.embedding_branch(features)
        
        features=l2_normal(features)
        # return attention_map,features
        if if_test:
            return attention_map,features
        patch_features=nn.functional.adaptive_avg_pool2d(features,output_size=region_output_size)
        
        region_features=features[:,np.newaxis,:,:,:]*attention_map[:,:,np.newaxis,:,:]
        region_features=torch.mean(region_features,(3,4))
        region_features=l2_normal(region_features,2)
        return l2_normal(patch_features),region_features,attention_map

In [104]:
de = decoder()

In [111]:
b=de(a)

torch.Size([2, 128, 64, 64])


In [113]:
b.shape

torch.Size([2, 32, 512, 512])